### ISSUE TITLE
Update to be compatible to latest GNOME version

### ISSUE THREAD

**Issue by jancborchardt** [dsboger/gnome-shell-extension-super-tab-launcher#2]
In the GNOME extensions platform, this app is marked as not being compatible with the current GNOME version, and it also doesn’t seem to work.

Would be awesome if it could be updated @dsboger

**Comment by dsboger** [comment]
The extension is compatible with GNOME Shell 3.22, which is the current version. Could you check what is the version of GS you are using? I don't have access to any other version to test if it works. It will be hard for me to debug such situations.

**Comment by dsboger** [comment]
I think this is not relevant anymore. Please reopen if needed.
