### ISSUE TITLE
Not compatible with AlternateTab

### ISSUE THREAD

**Issue by theychx** [dsboger/gnome-shell-extension-super-tab-launcher#3]
Hey. Thank you for making this extension, it's a really good idea.

It does however not work when the [AlternateTab](https://extensions.gnome.org/extension/15/alternatetab/) extension is also enabled. This means that I am stuck with the silly grouping behaviour of the default switcher, if I want to use your nice extension.

**Comment by dsboger** [comment]
Hi! Thanks for reporting!

When I first created the extension I thought it didn't make sense to add the launchers to the window switcher. But there is no harm in it either. I've pushed a commit that does that and it should work with alternate tab as well (since that extension simply rebinds Alt+Tab shortcut). Can you install from master and check if everything is working?

**Comment by theychx** [comment]
Works great. Thanks!

**Comment by dsboger** [comment]
I'm thinking about this enhancement and I'm in the mind of splitting the two mods into separate extensions: the current one only mods the app switcher and a new extension would mod the window switcher. This way one may choose either or both mods (without need of options that someone will certainly ask sooner or later :)). Also, the codes are independent anyway.

What do you think?

**Comment by theychx** [comment]
I personally would not mind the split, but I think it would be confusing to new gnome3 users who you could not expect to know the distinction between app switcher and window switcher. Besides, are there any dev related advantages to making this split?

PS: There is a reason that AlternateTab has had a permanent seat on the Top 10 of downloaded extensions for pretty much the entire lifespan of gnome3. The afore mentioned grouping behaviour is widely loathed, so in my view the window switcher functionality really is essential to this extension.
